version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  pipeline:
    build: .
    container_name: spotify_pipeline
    depends_on:
      - mongodb
    networks:
      - mongo_net

networks:
  mongo_net:

