version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  pipeline:
    build: .
    container_name: spotify_pipeline
    depends_on:
      - mongodb
    networks:
      - mongo_net

networks:
  mongo_net:

